name: flutter_service_bloc
description: Flutter package for service layer implement with bloc architecture
version: 0.1.0
homepage: https://github.com/aaassseee/service_bloc
repository: https://github.com/aaassseee/service_bloc/tree/main/flutter_service_bloc
issue_tracker: https://github.com/aaassseee/service_bloc/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: '>=8.0.0 <9.0.0'
#  service_bloc:
#    path: ../service_bloc
  service_bloc: '>=0.0.1 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
