name: flutter_service_bloc
description: Flutter package for service layer implement with bloc architecture
version: 4.0.0
homepage: https://github.com/aaassseee/service_bloc
repository: https://github.com/aaassseee/service_bloc/tree/main/flutter_service_bloc
issue_tracker: https://github.com/aaassseee/service_bloc/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: '>=9.0.0 <10.0.0'
#  service_bloc:
#    path: ../service_bloc
  service_bloc: '>=4.0.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: '>=10.0.0 <11.0.0'
  equatable: '>=2.0.0 <3.0.0'
  flutter_lints: '>=5.0.0 <6.0.0'
  mocktail: '>=1.0.0 <2.0.0'