name: example
description: An example application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: '>=9.0.0 <10.0.0'
  built_value: '>=8.0.0 <9.0.0'
  built_collection: '>=5.0.0 <6.0.0'
  http: '>=1.0.0 <2.0.0'
  service_bloc:
    path: ../

dev_dependencies:
  build_runner: '>=2.0.0 <3.0.0'
  built_value_generator: '>=8.0.0 <9.0.0'
  lints: '>=5.0.0 <6.0.0'
  test: '>=1.0.0 <2.0.0'
