name: example
description: An example application.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  built_value: ^8.4.2
  built_collection: ^5.1.1
  http: ^0.13.5
  service_bloc:
    path: ../../service_bloc

dev_dependencies:
  build_runner: ^2.3.2
  built_value_generator: ^8.4.2
  lints: ^2.0.0
  test: ^1.16.0
