name: service_bloc
description: Dart package for service layer implement with bloc architecture
version: 3.0.0-dev.0
homepage: https://github.com/aaassseee/service_bloc
repository: https://github.com/aaassseee/service_bloc/tree/main/service_bloc
issue_tracker: https://github.com/aaassseee/service_bloc/issues


environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: '>=8.0.0 <9.0.0'
  bloc_concurrency: '>=0.2.0 <1.0.0'
  equatable: '>=2.0.5 <3.0.0'
  meta: '>=1.8.0 <2.0.0'

dev_dependencies:
  test: ^1.21.6
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.0