name: service_bloc
description: Service implement with bloc pattern
version: 0.0.1
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: '>=8.0.0 <9.0.0'
  bloc_concurrency: '>=0.2.0 <1.0.0'
  equatable: '>=2.0.5 <3.0.0'
  meta: '>=1.8.0 <2.0.0'

dev_dependencies:
  test: ^1.21.6
  flutter_lints: ^2.0.0